version: 2
updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: weekly
    groups:
      server-dependencies:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /app
    schedule:
      interval: weekly
    groups:
      desktop-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
